/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as OrderInvoiceIdRouteImport } from './routes/order/$invoiceId'

const IndexLazyRouteImport = createFileRoute('/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderInvoiceIdRoute = OrderInvoiceIdRouteImport.update({
  id: '/order/$invoiceId',
  path: '/order/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/order/$invoiceId': typeof OrderInvoiceIdRoute
  '/order': typeof OrderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/order/$invoiceId': typeof OrderInvoiceIdRoute
  '/order': typeof OrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/order/$invoiceId': typeof OrderInvoiceIdRoute
  '/order/': typeof OrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/order/$invoiceId' | '/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/order/$invoiceId' | '/order'
  id: '__root__' | '/' | '/order/$invoiceId' | '/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  OrderInvoiceIdRoute: typeof OrderInvoiceIdRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$invoiceId': {
      id: '/order/$invoiceId'
      path: '/order/$invoiceId'
      fullPath: '/order/$invoiceId'
      preLoaderRoute: typeof OrderInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  OrderInvoiceIdRoute: OrderInvoiceIdRoute,
  OrderIndexRoute: OrderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
